version: '2'
services:
    postgres:
        image: mdillon/postgis
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - ${PATH_PREFIX}/db/data:/var/lib/postgresql/data
